title: Just the Octo
logo: "/assets/images/logo.png"
description: 一个简单、优雅的博客/文档模版!
baseurl: ''
url: https://obelusod.github.io/octo
theme: just-the-docs
lang: zh-CN

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

max_nav_depth: 4

remote_theme: just-the-docs/just-the-docs@v0.9.0
color_scheme: octo
search_enabled: true
heading_anchors: true
permalink: pretty
aux_links:
  GitHub:
    - https://github.com/Obelusod/octo
aux_links_new_tab: true

gh_edit_link: true
gh_edit_link_text: "在 GitHub 上编辑此页面"
gh_edit_repository: "https://github.com/Obelusod/octo"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

mermaid:
  version: "10.9.1"

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
