title: 网页模版
logo: "/assets/images/logo.png"
description: 一个简单的基础模版!
baseurl: ''
url: https://obelusod.github.io/octo
exclude: ["Gemfile", "Gemfile.lock", "vendor", "LICENSE", "README.md"]

max_nav_depth: 4

remote_theme: just-the-docs/just-the-docs
color_scheme: elegant
search_enabled: true
heading_anchors: true
permalink: pretty
aux_links:
  深色模式:
    - '#'
footer_content:

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
