title: Just the Octo
logo: "/assets/images/logo.png"
description: 一个简单、优雅的博客/文档模版!
baseurl: ''
url: https://obelusod.github.io/octo

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - vendor/
  - LICENSE
  - README.md

max_nav_depth: 4

remote_theme: just-the-docs/just-the-docs
color_scheme: octo
search_enabled: true
heading_anchors: true
permalink: pretty
aux_links:
  深色模式:
    - '#'
  GitHub:
    - https://github.com/Obelusod/octo
aux_links_new_tab: true

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
